import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>My Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          {/* Tulisan Welcome */}
          <p>
            Welcome to proyek awal!
          </p>
          <div>
            {/* Link ke LinkedIn */}
              By Maulana Izzudin Faqih
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            title='Nextjs logo'
            src="/next.svg"
            alt="Nextjs Logo"
            width={300}
            height={150}
            priority
          />
        </div>

        <h2>
          Ini kontak yang bisa dihubungi ya!
        </h2>
        <br></br>

        <div className={styles.grid}>
          <a
            href="https://www.instagram.com"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              <Image
              className={styles.instagram}
              title='Instagram'
              src="/instagram-logo.png"
              alt="Instagram"
              width={25}
              height={25}
            />
              {''} Instagram {''}<span>-&gt;</span>
            </h2>
            <p>
              Linknya nanti ke Instagram utamaku, btw aku punya sec acc lho!
            </p>
          </a>

          <a
            href="https://github.com/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
            <Image
              className={styles.instagram}
              title='Github'
              src="/github-logo1.png"
              alt="Github"
              width={25}
              height={25}
            />
              {''} Github <span>-&gt;</span>
            </h2>
            <p>
              Ini nanti ke akun Github aku, tapi aku lupa id ama passwordnya :(
            </p>
          </a>

          <a
            href="https://twitter.com/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
            <Image
              className={styles.instagram}
              title='Twitter'
              src="/logo-twitter.png"
              alt="Twitter logo"
              width={25}
              height={25}
            />
              {''} Twitter <span>-&gt;</span>
            </h2>
            <p>
              Biasanya aku lebih aktif di twitter juga lho!
            </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
            <Image
              className={styles.instagram}
              title='Whatsapp'
              src="/logo-whatsapp.png"
              alt="Whatsapp logo"
              width={25}
              height={25}
            />
              {''} Whatsapp <span>-&gt;</span>
            </h2>
            <p>
              Bisa juga langsung ke Whatsapp Pribadiku :D
            </p>
          </a>

          <a 
            href="https://www.linkedin.com/in/maulana-izzudin-faqih-90902a232/overlay/contact-info"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
            <Image
              className={styles.instagram}
              title='LinkedIn'
              src="/linkedin-logo.png"
              alt="Whatsapp logo"
              width={25}
              height={25}
            />
              {''} LinkedIn <span>-&gt;</span>
            </h2>
            <p>
              LinkedIn punyaku, masih berantakan btw
            </p>
          </a>
        </div>
        <br></br>
        <br></br>
        
        <div className={styles.button}>
          <a
            href='/page-kalkulator'
            target="_blank"
          >
            <h2>
            Klik disini untuk mencoba kalkulator!
            </h2>
          </a>
        </div>
        
      </main>
    </>
  )
}
